version: 2
updates:
  # Grouping NPM (Express, Puppeteer, etc.)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  # Grouping Docker (The puppeteer base image)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  # Grouping GitHub Actions (Checkout, SSH action, etc.)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-dependencies:
        patterns:
          - "*"